language: swift

osx_image: xcode12

xcode_project: IGStoriesView.xcodeproj # path to your xcodeproj folder
xcode_scheme: IGStoriesView
xcode_destination: platform=iOS Simulator,OS=14,name=iPhponeX
script:
  - xcodebuild -scheme IGStoriesView -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=14' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
