language: swift

osx_image: xcode11.6

xcode_project: IGStoriesView.xcodeproj
xcode_scheme: IGStoriesView
xcode_sdk: iphonesimulator13.6 #5
script:
  - set -o pipefail && xcodebuild -project IGStoriesView.xcodeproj -scheme IGStoriesView -sdk iphonesimulator13.6 build test ONLY_ACTIVE_ARCH=YES
script:
  - xcodebuild test -project IGStoriesView.xcodeproj -scheme IGStoriesView -sdk iphonesimulator14.0 -destination 'platform=iOS Simulator,name=iPhone 11,OS=14'
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1e04617f-5c2e-4ffc-91d6-9544a9e9302b
