language: swift

osx_image: xcode12

script:
  - xcodebuild test -project IGStoriesView.xcodeproj -scheme IGStoriesView -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=14'
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 1e04617f-5c2e-4ffc-91d6-9544a9e9302b
