language: swift
osx_image: xcode12
script:
  - xcodebuild clean build test -project IGStoriesView.xcodeproj -scheme IGStoriesView -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.0,name=iPhone 11" ONLY_ACTIVE_ARCH=NO CODE_SIGN=NO
after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
